import React from 'react';
import { ArrowUpRight, CheckCircle2, ChevronRight, Code2, GraduationCap, Landmark, Monitor, Sparkles, Target, UsersRound } from 'lucide-react';
import { Link } from 'react-router-dom';
import SectionTitle from '../components/SectionTitle';
import { services, site } from '../data/siteData';

const featured = services.slice(0, 6);
const icons = { 0: GraduationCap, 1: GraduationCap, 2: CheckCircle2, 3: Monitor, 4: Monitor, 5: Landmark };

export default function Home() {
  return <>
    <section className="relative overflow-hidden bg-ink text-white">
      <div className="absolute inset-0 grid-overlay opacity-25" /><div className="hero-orb right-[-140px] top-[-40px] h-[34rem] w-[34rem] bg-gold/20 blur-3xl" />
      <div className="container-shell relative grid items-center gap-10 py-10 sm:py-16 md:grid-cols-[1.08fr_.92fr] md:py-24">
        <div>
          <span className="inline-flex items-center gap-2 rounded-full border border-white/10 bg-white/5 px-3 py-1.5 text-[10px] font-extrabold uppercase tracking-[.2em] text-slate-300"><Sparkles size={13} className="text-gold" /> One place. Many solutions.</span>
          <h1 className="mt-6 max-w-4xl text-balance font-display text-5xl leading-[.98] sm:text-6xl md:text-7xl">Education. <span className="text-gold">Guidance.</span><br />Digital solutions.</h1>
          <p className="mt-6 max-w-2xl text-sm leading-7 text-slate-300 sm:text-base md:text-lg md:leading-8">Saranesh Edu Hub Coaching Classes helps students with coaching and tuition, supports admission and online processes, and provides everyday digital and technology services.</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link to="/services" className="inline-flex items-center justify-center gap-2 rounded-full bg-gold px-6 py-3.5 text-sm font-extrabold text-ink shadow-glow">Explore Services <ArrowUpRight size={17} /></Link><Link to="/counsellor" className="inline-flex items-center justify-center gap-2 rounded-full border border-white/15 bg-white/5 px-6 py-3.5 text-sm font-bold text-white">Book a Counsellor <ChevronRight size={17} /></Link></div>
          <div className="mt-8 grid grid-cols-3 gap-2 sm:gap-3">{[['01', 'Classes 1st–10th'], ['02', 'Admission & Forms'], ['03', 'Digital & Tech']].map(([n, l]) => <div key={l} className="rounded-2xl border border-white/10 bg-white/5 p-3 sm:p-4"><div className="font-display text-2xl sm:text-3xl">{n}</div><div className="mt-1 text-[10px] font-bold uppercase tracking-[.11em] text-slate-400">{l}</div></div>)}</div>
        </div>
        <div className="relative"><div className="absolute -inset-5 rounded-[2.5rem] bg-gold/10 blur-2xl" /><div className="relative flex min-h-[420px] items-center justify-center overflow-hidden rounded-[2rem] border border-white/10 bg-white/10 p-6 shadow-2xl backdrop-blur-xl sm:min-h-[520px]"><div className="absolute inset-0 bg-[radial-gradient(circle_at_30%_30%,rgba(220,174,74,.18),transparent_35%),radial-gradient(circle_at_70%_70%,rgba(255,255,255,.08),transparent_40%)]" /><img src="/assets/logo.png" alt="Saranesh Edu Hub logo" className="relative h-56 w-56 object-contain drop-shadow-2xl sm:h-72 sm:w-72" /><div className="absolute bottom-5 left-5 right-5 rounded-2xl border border-white/10 bg-ink/80 p-4 backdrop-blur-xl sm:bottom-7 sm:left-7 sm:right-7"><div className="text-[10px] font-extrabold uppercase tracking-[.18em] text-gold">Saranesh Edu Hub</div><div className="mt-2 font-display text-xl sm:text-2xl">Learning + Services + Solutions</div></div></div></div>
      </div>
    </section>

    <section className="border-b border-slate-200 bg-white"><div className="container-shell grid grid-cols-2 divide-x divide-y divide-slate-200 sm:grid-cols-4 sm:divide-y-0">{[['01', 'Coaching'], ['02', 'Admissions'], ['03', 'Digital Services'], ['04', 'Technology']].map(([n, t]) => <div key={t} className="flex items-center gap-3 px-3 py-5 sm:px-5 sm:py-7"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-ink text-xs font-extrabold text-gold">{n}</span><span className="text-xs font-extrabold uppercase tracking-[.08em] text-slate-600 sm:text-sm">{t}</span></div>)}</div></section>

    <section className="py-16 sm:py-20 md:py-24"><div className="container-shell"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><SectionTitle eyebrow="What we do" title="A practical mix of education, online support and modern services." text="The service list follows the client requirements closely — from classes and admissions to forms, cyber services, property information and software development." /><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{featured.map((item, index) => { const Icon = icons[index] || CheckCircle2; return <Link to="/services" key={item.no} className="group rounded-[1.6rem] border border-slate-200 bg-white p-5 shadow-soft transition hover:-translate-y-1 hover:border-gold/50"><div className="flex items-start justify-between gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-ink text-gold group-hover:bg-gold group-hover:text-ink"><Icon size={19} /></div><ChevronRight size={18} className="text-slate-300 transition group-hover:translate-x-1" /></div><h3 className="mt-5 font-display text-2xl leading-tight">{item.title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{item.short}</p></Link> })}</div></div></div></section>

    <section className="bg-[#eeeae1] py-16 sm:py-20 md:py-24"><div className="container-shell grid gap-10 lg:grid-cols-[1.1fr_.9fr] lg:items-center"><div><SectionTitle eyebrow="Why Saranesh Edu Hub" title="One trusted point of contact for learning and everyday digital needs." text="Students and families can reach out for education support, admission processes, government/job forms, general online work and other services shared in the client brief." /><div className="mt-7 grid gap-3 sm:grid-cols-2">{['Classes & tuition for 1st to 10th', 'Admission & education guidance', 'Online forms & registration support', 'Government & job form assistance', 'Cyber / print / scan support', 'Website & business app development'].map(x => <div key={x} className="flex items-center gap-3 rounded-2xl border border-black/5 bg-white/75 p-4 text-sm font-bold text-slate-700"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-gold text-ink"><CheckCircle2 size={16} /></span>{x}</div>)}</div></div><div className="rounded-[2rem] bg-ink p-6 text-white shadow-soft sm:p-8"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-gold text-ink"><Code2 size={21} /></div><div className="mt-5 text-xs font-extrabold uppercase tracking-[.2em] text-gold">Technology services</div><h3 className="mt-3 font-display text-3xl">Need a website or business app?</h3><p className="mt-3 text-sm leading-7 text-slate-300">Saranesh Edu Hub also offers software development, websites and business-related applications.</p><Link to="/contact" className="mt-6 inline-flex items-center gap-2 rounded-full bg-white px-5 py-3.5 text-sm font-extrabold text-ink">Discuss a requirement <ArrowUpRight size={17} /></Link></div></div></section>

    <section className="py-16 sm:py-20"><div className="container-shell"><div className="rounded-[2rem] bg-ink px-5 py-10 text-white sm:px-8 md:px-12 md:py-14"><div className="grid items-center gap-8 lg:grid-cols-[1fr_auto]"><div><div className="text-xs font-extrabold uppercase tracking-[.2em] text-gold">Contact Saranesh Edu Hub</div><h2 className="mt-3 font-display text-3xl sm:text-4xl">Education, online work or digital support?</h2><p className="mt-3 max-w-2xl text-sm leading-7 text-slate-300">Call {site.phone} or send an enquiry online and share what you need.</p></div><Link to="/contact" className="inline-flex items-center justify-center gap-2 rounded-full bg-gold px-6 py-3.5 text-sm font-extrabold text-ink">Get in touch <ArrowUpRight size={17} /></Link></div></div></div></section>
  </>;
}
